### ISSUE TITLE
Code and models release?

### ISSUE THREAD

**Issue by vishaal27** [YunxinLi/LingCloud#1]
Thanks for your great pre-print, do you have an estimated timeline for when LMEye checkpoints will be released? I am especially interested in the BLOOM-z-7B and LLaMA-7B based models.

**Comment by YunxinLi** [comment]
Soon, I'll let you know once the codes and checkpoints are released.

**Comment by YunxinLi** [comment]
> 

Thanks, we have released the code and data.
